[[redirects]]
from = "/about.html"
to = "/html/about.html"
status = 200

[[redirects]]
from = "/history.html"
to = "/html/history.html"
status = 200

[[redirects]]
from = "/accreditation.html"
to = "/html/accreditation.html"
status = 200

[[redirects]]
from = "/state.html"
to = "/html/state.html"
status = 200

[[redirects]]
from = "/lecturers.html"
to = "/html/lecturers.html"
status = 200

[[redirects]]
from = "/lecturer.html"
to = "/html/lecturer.html"
status = 200

[[redirects]]
from = "/partners.html"
to = "/html/partners.html"
status = 200

[[redirects]]
from = "/international_coop.html"
to = "/html/international_coop.html"
status = 200

[[redirects]]
from = "/alumni.html"
to = "/html/alumni.html"
status = 200

[[redirects]]
from = "/alumnus.html"
to = "/html/alumnus.html"
status = 200

[[redirects]]
from = "/document_circulation.html"
to = "/html/document_circulation.html"
status = 200

[[redirects]]
from = "/online_studying.html"
to = "/html/online_studying.html"
status = 200

[[redirects]]
from = "/admission.html"
to = "/html/admission.html"
status = 200

[[redirects]]
from = "/speciality.html"
to = "/html/speciality.html"
status = 200

[[redirects]]
from = "/admission-zno.html"
to = "/html/admission-zno.html"
status = 200

[[redirects]]
from = "/admission-junior-specialist.html"
to = "/html/admission-junior-specialist.html"
status = 200

[[redirects]]
from = "/admission-master.html"
to = "/html/admission-master.html"
status = 200

[[redirects]]
from = "/admission-postgraduate.html"
to = "/html/admission-postgraduate.html"
status = 200

[[redirects]]
from = "/admission-external.html"
to = "/html/admission-external.html"
status = 200

[[redirects]]
from = "/admission-preparatory-courses.html"
to = "/html/admission-preparatory-courses.html"
status = 200

[[redirects]]
from = "/student.html"
to = "/html/student.html"
status = 200

[[redirects]]
from = "/bachelor.html"
to = "/html/bachelor.html"
status = 200

[[redirects]]
from = "/bachelor_practice.html"
to = "/html/bachelor_practice.html"
status = 200

[[redirects]]
from = "/bachelor_diploma_design.html"
to = "/html/bachelor_diploma_design.html"
status = 200

[[redirects]]
from = "/master.html"
to = "/html/master.html"
status = 200

[[redirects]]
from = "/postgraduate.html"
to = "/html/postgraduate.html"
status = 200

[[redirects]]
from = "/online_studying_sources.html"
to = "/html/online_studying_sources.html"
status = 200

[[redirects]]
from = "/student_council.html"
to = "/html/student_council.html"
status = 200

[[redirects]]
from = "/leisure.html"
to = "/html/leisure.html"
status = 200

[[redirects]]
from = "/dormitory.html"
to = "/html/dormitory.html"
status = 200

[[redirects]]
from = "/science.html"
to = "/html/science.html"
status = 200

[[redirects]]
from = "/science_schools.html"
to = "/html/science_schools.html"
status = 200

[[redirects]]
from = "/contacts.html"
to = "/html/contacts.html"
status = 200

[[redirects]]
from = "/news_main.html"
to = "/html/news_main.html"
status = 200

[[redirects]]
from = "/news_article.html"
to = "/html/news_article.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200