[[redirects]]
from = "/about.html"
to = "/html/about.html"
status = 200

[[redirects]]
from = "/history.html"
to = "/html/history.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200